[build]
  base = "netlify"
  publish = "build/site"
  command = "node_modules/.bin/docs --html-url-extension-style=indexify --pull ../antora-site.yml"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/docs"

[context.production.environment]

[context.deploy-preview]
  command = "URL=$DEPLOY_PRIME_URL node_modules/.bin/docs --html-url-extension-style=indexify --pull ../antora-site.yml"
